@Forecast_HostAddress = http://localhost:5146

GET {{Forecast_HostAddress}}/api/coordinates/
Accept: application/json

###

POST {{Forecast_HostAddress}}/api/coordinates/
Accept: application/json
Content-Type: application/json
{
      "latitude": 32.3236,
      "longitude": 17.1713
}

###
DELETE {{Forecast_HostAddress}}/api/coordinates/32.323617.1713
Accept: application/json

###
GET {{Forecast_HostAddress}}/api/forecast?latitude=37.7749&longitude=-122.4194
Accept: application/json

###
POST {{Forecast_HostAddress}}/api/forecast/
Accept: application/json
Content-Type: application/json
{
      "latitude": 32.3236,
      "longitude": 17.1713,
      "temperature": 21,
      "time": "2022-01-01T15:00"
}