// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sofomo.Coordinates.Data.Migrations
{
    [DbContext(typeof(CoordinatesDbContext))]
    partial class CoordinatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Coordinates")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sofomo.Coordinates.Coordinates", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coordinates", "Coordinates");

                    b.HasData(
                        new
                        {
                            Id = "51.117264217.0215266",
                            Latitude = 51.117264200000001,
                            Longitude = 17.021526600000001
                        },
                        new
                        {
                            Id = "51.097817.032707",
                            Latitude = 51.097799999999999,
                            Longitude = 17.032706999999998
                        },
                        new
                        {
                            Id = "51.107550417.0690172",
                            Latitude = 51.107550400000001,
                            Longitude = 17.069017200000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
